### ISSUE TITLE
Options usage

### ISSUE THREAD

**Issue by llrs** [llrs/bugzilla_viz#1]
I don't understand why you omit warnings. The code should run without warnings, if you are omitting some something might go wrong with the script or the analysis. 

https://github.com/llrs/bugzilla_viz/blob/9896ce61fffc860a623457221fe2855526e453dc/bugRzilla_review_script.R#L1

**Comment by kpiyush04** [comment]
> I don't understand why you omit warnings. The code should run without warnings, if you are omitting some something might go wrong with the script or the analysis.
> 
> https://github.com/llrs/bugzilla_viz/blob/9896ce61fffc860a623457221fe2855526e453dc/bugRzilla_review_script.R#L1

I'll remove it.
